/* Generated by Together */

#ifndef SUBMAP_H
#define SUBMAP_H
#include "App/GameAppNet.h"
// tchar.h нужен только на Windows; TCHAR даёт словарь совместимости.
#include "PlatformCompat.h"
#include <stdio.h>
#include "Entity/EntitySpawn.h"
#include "World/SwitchMapRecord.h"
#include "Network/CompCommand.h"
#include "Item/Item.h"
#include "Combat/Range.h"
#include "World/EyeshotCell.h"
#include "World/StateCell.h"
#include "World/StateCellGrid.h"
#include "World/Weather.h"
#include "App/GameApp.h"
#include "World/MapRes.h"

#define defRANGE_MGRUNIU_NUM	10000

class MgrUnit;
class CActiveMgrUnitL;
class Entity;
class CFightAble;

//
class COutMapCha {
public:
	struct SMgrUnit {
		bool IsValidCha(void) {
			if (!pCCha) return false;
			return pCCha->GetID() == ulChaID;
		}

		std::int32_t lLeftTick1; //
		std::int32_t lLeftTick2; //
		char chAction; //
		CCharacter* pCCha;
		std::uint32_t ulChaID;
		SSwitchMapInfo SwitchInfo;
		char chStep;

		SMgrUnit* pSNext;
	};

	COutMapCha(unsigned short usFreq = 2000);
	~COutMapCha();

	void Add(CCharacter* pCObj, std::uint32_t ulChaID, SSwitchMapInfo* pSwitchInfo, char chAction,
			 std::int32_t lLeftTick1, std::int32_t lLeftTick2);
	void Run(unsigned long ulCurTick);
	void Drop();
	void ExecTimeCha(SMgrUnit* pChaInfo);
	std::deque<std::unique_ptr<SMgrUnit>> spawnQueue; // Spawn queue rework - Mdr
private:
	unsigned long m_ulTick;
	unsigned short m_usFreq; //
};

//
class SubMap {
public:
	SubMap();
	virtual ~SubMap();

	bool Init(CMapRes* pCMapRes, int16_t sCopyNO = 0);

	bool         IsRun(void);
	const char*  GetName(void);

	//pt.
	Corsairs::Util::Rect GetEyeshot(Corsairs::Util::Point& pt) const;
	Corsairs::Util::Rect GetEyeshot(short sMgrUnitX, short sMgrUnitY) const;
	void GetEyeshotCenter(Corsairs::Util::Point& pt);
	Corsairs::Util::Rect GetHoldStateCell(Corsairs::Util::Point& pt, std::int32_t lRadius) const;
	void GetHoldStateCellCenter(Corsairs::Util::Point& pt);

	void Add(Entity* ent);
	void Delete(Entity* ent);
	void MoveInStateCell(CCharacter* pCCha, const Corsairs::Util::Point& SSrcPos, const Corsairs::Util::Point& STarPos);
	void MoveInMapMask(CCharacter* pCCha, const Corsairs::Util::Point& SSrcPos, const Corsairs::Util::Point& STarPos);

	bool EnsurePos(Corsairs::Util::Square* pSEntShape, Entity* ent, const int32_t clSearchRadius = 40 * 100);
	bool Enter(Corsairs::Util::Square* pSEntShape, Entity* ent, const int32_t clSearchRadius = 40 * 100);
	void GoOut(Entity* ent);
	void MoveTo(Entity* pCEnt, const Corsairs::Util::Point& STar);
	void RefreshEyeshot(Entity* pCEnt, bool bEyeshot, bool bHide, bool bShow);

	bool         IsValidPos(std::int32_t lPosX, std::int32_t lPosY);

	std::uint16_t  GetAreaAttr(std::int32_t lPosX, std::int32_t lPosY);
	std::uint16_t  GetAreaAttr(const Corsairs::Util::Point& Pos);

	void NotiStateCellToEyeshot(int16_t sCellX, int16_t sCellY);

	//
	void BeginSearchInRange(std::int32_t* plRangeBParam, std::int32_t* plRangeEParam, bool bIncludeHideEnti = false);
	CCharacter* GetNextCharacterInRange(void);

	//
	bool RangeAddState(std::uint8_t uchFightID, std::uint32_t ulSrcWorldID, std::int32_t lSrcHandle,
					   char chObjType, char chObjHabitat, char chEffType, int16_t* sStateParam);
	bool RangeAddState(Corsairs::Util::Rect* pSRange, std::uint8_t uchFightID, std::uint32_t ulSrcWorldID, std::int32_t lSrcHandle,
					   char chObjType, char chObjHabitat, char chEffType, int16_t* sStateParam);

	//
	CCharacter* FindCharacter(std::uint32_t ulID, const Corsairs::Util::Point& point);
	//
	bool IsMoveAble(Entity* pCEnt, std::int32_t lPosX, std::int32_t lPosY);

	void LoadMonsterInfo(void);

	BOOL LoadNpc();

	BOOL LoadEventEntity();

	Corsairs::Common::NPC::CNpcRecord* GetNpcInfo(USHORT sNpcID);

	CItem* ItemSpawn(const SItemGrid* pItemInfo, std::int32_t lPosX, std::int32_t lPosY, char chSpawnType,
					 std::int32_t lFromEntityID = 0, std::int32_t lProtChaID = 0, std::int32_t lProtChaHandle = 0,
					 std::int32_t lProtTime = 0, std::int32_t lOnTick = 0,
					 CEvent* pCEvent = NULL);
	CCharacter* ChaSpawn(std::int32_t lChaInfoID, Corsairs::Common::Character::EChaCtrlType chCtrlType, int16_t sAngle, Corsairs::Util::Point* pSPos,
						 bool bEyeshotAbility = false,
						 const char* cszChaName = 0, const long clSearchRadius = 120 * 100);

	void EntryOpen(void);
	void EntryClose(void);
	void Open(void);
	void Run(DWORD dwCurTime);
	void Close(void);
	void ClearSurfaceState(void);
	void ResetNotPlyCha(void);
	void ClearPlayerCha(void);
	void ClearAllCha(void);
	void ClearAllMonster(void);
	void ClearAllMonsterByName(const char* szMonsName);
	void Notice(const char* szString);

	int16_t   GetEyeshotCellWidth(void) const;
	int16_t   GetEyeshotCellHeight(void) const;
	int16_t   GetEyeshotCellLin(void) const;
	int16_t   GetEyeshotCellCol(void) const;

	int16_t   GetStateCellWidth(void) const;
	int16_t   GetStateCellHeight(void) const;
	int16_t   GetStateCellLin(void) const;
	int16_t   GetStateCellCol(void) const;

	int16_t   GetBlockCellWidth(void) const;
	int16_t   GetBlockCellHeight(void) const;

	bool         GetTerrainCellSize(int16_t* psWidth, int16_t* psHeight);
	bool         GetTerrainCellAttr(int16_t sUnitX, int16_t sUnitY, std::uint16_t& usAttribute);
	bool         GetTerrainCellIsland(int16_t sUnitX, int16_t sUnitY, std::uint8_t& uchIsland);

	BYTE         IsBlock(std::int32_t lCellX, std::int32_t lCellY);

	const Corsairs::Util::Rect&  GetRange(void) const;

	BYTE         GetMapID();

	int16_t   GetEyeshotWidth(void) const;

	bool         CanPK(void);
	bool         CanSavePos(void);

	void BeforePlyOutMap(CCharacter* pCCha);
	void AfterPlyEnterMap(CCharacter* pCCha);

	std::int32_t    GetMonsterNum(void);

	CMapRes*     GetMapRes(void);

	void         SetCopyNO(int16_t sCopyNO);
	int16_t   GetCopyNO(void);

	std::int32_t    GetPlayerNum(void);

	std::int32_t    GetInfoParam(char chParamID);
	bool         SetInfoParam(char chParamID, std::int32_t lParamVal);

	void BeginGetPlyCha(void);
	CCharacter* GetNextPlyCha(void);
	bool CheckRun(void);
	void DealActivePlayer(std::string& function); //2006.10.12wsj.
	void DealPlayer(std::string& function);

	void         SetSpecialInter(int interva); //2006.10.12wsj

	std::int32_t    GetActivePlayer(); //2006.10.12wsj

	std::int32_t CountEyeshotPlyActiveNum(std::int32_t lCellX, std::int32_t lCellY);

	void         ActiveEyeshotCell(std::int32_t lCellX, std::int32_t lCellY);
	void         InactiveEyeshotCell(std::int32_t lCellX, std::int32_t lCellY);

	bool         IsValidStateCell(std::int32_t x, std::int32_t y);

	CChaListNode* StateCellAddCha(std::int32_t lCellX, std::int32_t lCellY, CCharacter* pCCha, bool bIn);
	void          StateCellDelCha(std::int32_t lCellX, std::int32_t lCellY, CChaListNode* pCChaNode);

	void          ActiveStateCell(std::int32_t lCellX, std::int32_t lCellY);
	void          InactiveStateCell(std::int32_t lCellX, std::int32_t lCellY);

	bool AddCellState(std::uint8_t uchFightID, std::uint32_t ulSrcWorldID, std::int32_t lSrcHandle, char chObjType,
					  char chObjHabitat, char chEffType,
					  std::int32_t lCellX, std::int32_t lCellY, std::uint8_t uchStateID, std::uint8_t uchStateLv,
					  std::uint32_t ulStartTick, std::int32_t lOnTick, char chType, char chWithCenter);

	void          ReleaseStateCell(std::int32_t x, std::int32_t y);

	CEyeshotCell** m_pCEyeshotCell; //
	StateCellGrid _stateCellGrid; //
	COutMapCha m_COutMapCha; //
	//
	CActEyeshotCell m_CEyeshotCellL; //
	CActStateCell m_CStateCellL; //

	bool m_bIsRun; //
	CWeatherMgr m_WeatherMgr; //

private:
	CMapRes* m_pCMapRes;
	CTimer m_timeSpecialRun;

	void CheckStateCell(std::int32_t x, std::int32_t y);

	//
	struct {
		bool m_bIncludeHideEnti; //
		int16_t m_sRangeMgrUnitNum; //
		std::int32_t m_lRangeMgrUnit[defRANGE_MGRUNIU_NUM][2]; // x,y
		std::int32_t m_lRangeCentUnit[2]; // ;
		int16_t m_sRangeCurMgrUnit; //
		CChaListNode* m_pRangeCurEntiNode; //
		CRangeBase* m_pCBaseRange;

		CRangeStick m_CStickRange;
		CRangeFan m_CFanRange;
		CRangeSquare m_CSquareCRange;
		CRangeCircle m_CCircleRange;
	};

	int16_t m_sCopyNO;
	CTimer m_timeScriptRun;

	std::int32_t m_lPlayerNum;
	//	std::int32_t	m_lActivePlayerNum;
	std::int32_t m_lInfoParam[defMAPCOPY_INFO_PARAM_NUM];
};

#endif //SUBMAP_H
