/* Generated by Together */
#include "Core/stdafx.h"
#include <algorithm>

#include "App/GameServerApp.h"
#include <iostream>

#include <time.h>
#include "Network/NetCommand.h"
#include "Network/NetRetCode.h"
#include "Core/RoleCommon.h"
#include "Network/CompCommand.h"
#include "Core/CommFunc.h"
#include "World/SubMap.h"
#include "App/GameApp.h"

extern BOOL	g_bGameEnd;

//
//  GateHandler  callback'  TcpClient (CorsairsNet)
// 

void GateHandler::OnPacket(Corsairs::Net::RPacket& packet)
{
    GateServer* gt = &_app->m_gtarray[_gateIndex];
    if (!gt->IsValid()) return;
    _app->ProcessData(gt, packet);
}

void GateHandler::OnDisconnected(int reason)
{
    //  recv thread    ,   game thread
    _app->m_pendingDisconnect.store(_gateIndex);
}

// 
//  GameServerApp   / 
// 

GameServerApp::GameServerApp()
    : m_count(0)
{
	ToLogService("common", "start init ServerApp");

	srand( (unsigned)time( NULL ) );

    m_strGameName = g_Config.m_szName;

    //  GateServer 
    // std::min вместо макроса min из windows.h — он есть только на Windows.
    m_gtnum = std::min(MAX_GATE, g_Config.m_nGateCnt);
    for (int i = 0; i < m_gtnum; ++i)
    {
        m_gtarray[i].GetIP() = g_Config.m_szGateIP[i];
        m_gtarray[i].GetPort() = g_Config.m_nGatePort[i];
        m_gateHandlers[i].Init(i, this);
        m_gateClients[i].SetHandler(&m_gateHandlers[i]);
    }

    //
    m_connectThread = std::thread(&GameServerApp::ConnectGateLoop, this);

	ToLogService("common", "ServerApp init over");
}

GameServerApp::~GameServerApp()
{
    //
    m_exitFlag.store(true);
    if (m_connectThread.joinable())
        m_connectThread.join();

    //   GateServer'
    for (int i = 0; i < m_gtnum; ++i)
    {
        m_gateClients[i].Disconnect();
        m_gtarray[i].Invalid();
    }
}

// 
//  ConnectGateLoop     ( ConnectGateServer::Process)
// 

void GameServerApp::ConnectGateLoop()
{
    DWORD dwInterval = 5000;

    while (!m_exitFlag.load())
    {
        for (int i = 0; i < 1; i++)
        {
            if (m_exitFlag.load()) return;

            if (!m_gtarray[i].IsValid() && !m_gateClients[i].IsConnected())
            {
                ToLogService("network", "connecting to GateServer {}:{}...",
                    m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort());

                if (m_gateClients[i].Connect(m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort()))
                {
                    m_gtarray[i].SetClient(&m_gateClients[i]);
                    //  game thread   
                    m_pendingConnect.store(i);
                    ToLogService("network", "GateServer connected: {}:{}",
                        m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort());
                }
                else
                {
                    ToLogService("network", "connect to GateServer failed, ip = {}, port = {}.",
                        m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort());
                }
            }
        }
        Sleep(dwInterval);
    }
}

// 
//  HandlePendingEvents   connect/disconnect  game thread
// 

void GameServerApp::HandlePendingEvents()
{
    //  pending connect
    int ci = m_pendingConnect.exchange(-1);
    if (ci >= 0 && ci < m_gtnum)
    {
        GateServer* gt = &m_gtarray[ci];
        //  :    GateServer
        auto wpkt = Corsairs::Net::Msg::serializeGmGateConnectCmd();
        Corsairs::Net::RPacket rpkt(wpkt.Data(), wpkt.GetPacketSize(), false);
        g_pGameApp->ProcessNetMsg(NETMSG_GATE_CONNECTED, gt, rpkt);
    }

    //  pending disconnect
    int di = m_pendingDisconnect.exchange(-1);
    if (di >= 0 && di < m_gtnum)
    {
        auto const lock = std::lock_guard{m_mutdisconn};
        GateServer* gt = &m_gtarray[di];
        if (gt->IsValid() || !gt->m_playerlist.empty())
        {
            //  :     Gate  GateServer
            auto wpkt = Corsairs::Net::Msg::serializeGmGateDisconnect(0);
            Corsairs::Net::RPacket rpkt(wpkt.Data(), wpkt.GetPacketSize(), false);
            g_pGameApp->ProcessNetMsg(NETMSG_GATE_DISCONNECT, gt, rpkt);
        }
    }
}

// 
//  PeekPacket    gate- ( PKQueue::PeekPacket)
// 

void GameServerApp::PeekPacket(unsigned long ms)
{
    DWORD start = GetTickCount();

    do
    {
        HandlePendingEvents();

        int processed = 0;
        for (int i = 0; i < m_gtnum; i++)
        {
            if (m_gateClients[i].IsConnected())
                processed += m_gateClients[i].PollPackets(50);
        }

        DWORD elapsed = GetTickCount() - start;
        if (elapsed >= ms) break;

        if (processed == 0) Sleep(1);

    } while (true);
}

// 
//  DisconnectGate   GateServer
// 

void GameServerApp::DisconnectGate(GateServer* pGate)
{
    if (pGate == nullptr) return;

    //   GateServer
    for (int i = 0; i < m_gtnum; ++i)
    {
        if (&m_gtarray[i] == pGate)
        {
            m_gateClients[i].Disconnect();
            pGate->Invalid();
            return;
        }
    }
}

// 
//  ProcessData    ( PKQueue  ProcessData)
// 

void GameServerApp::ProcessData(GateServer* gt, Corsairs::Net::RPacket& pk)
{
    if (gt == nullptr) return;

    uint16_t cmd = pk.GetCmd();

    // OnServeCall-: SESS-echo (  C++  .NET GateServer)
    if (cmd == CMD_TM_KICKCHA || cmd == CMD_TM_OFFLINE_MODE)
    {
        HandleServeCall(gt, pk);
        return;
    }

    int msg_id;
    switch (cmd)
    {
        case CMD_MM_GATE_CONNECT:
		    ToLogService("network", "ProcessData Gate_Connect");
            msg_id = NETMSG_GATE_CONNECTED;
            break;

        case CMD_MM_GATE_RELEASE:
            msg_id = NETMSG_GATE_DISCONNECT;
            break;

        default:
            msg_id = NETMSG_PACKET;
            break;
    }

    g_pGameApp->ProcessNetMsg(msg_id, gt, pk);
}

//
//  HandleServeCall   sync-  SESS-echo
// 

void GameServerApp::HandleServeCall(GateServer* gt, Corsairs::Net::RPacket& pk)
{
    uint32_t sess = pk.GetSess();
    uint16_t cmd = pk.GetCmd();

    Corsairs::Net::WPacket retpk(256);
    retpk.WriteSess(sess);

    switch (cmd)
    {
    case CMD_TM_KICKCHA:
    {
        auto const m = std::lock_guard{m_mutdisconn};
        Corsairs::Net::Msg::TmKickChaMessage kickMsg;
        Corsairs::Net::Msg::deserialize(pk, kickMsg);
        long lChaDbID = static_cast<long>(kickMsg.charDbId);
        CPlayer* pCOldPly = g_pGameApp->FindPlayerByDBChaID(lChaDbID);
        if (!pCOldPly || !pCOldPly->IsValid())
        {
            retpk.WriteInt64(0);
        }
        else
        {
            pCOldPly->GetCtrlCha()->BreakAction();
            pCOldPly->MisLogout();
            pCOldPly->MisGooutMap();
            g_pGameApp->ReleaseGamePlayer(pCOldPly);
            retpk.WriteInt64(1);
        }
        break;
    }
    case CMD_TM_OFFLINE_MODE:
    {
        Corsairs::Net::Msg::TmOfflineModeMessage offlineMsg;
        Corsairs::Net::Msg::deserialize(pk, offlineMsg);
        auto player = Corsairs::Util::ToPointer<CPlayer>(offlineMsg.playerPtr);
        CCharacter* pCCha{};

        const auto return_code = [&]
        {
            if (!player)
                return ReturnCode::OfflineMode::Unknown;

            if (player->GetGateAddr() != static_cast<DWORD>(offlineMsg.gateAddr))
                return ReturnCode::OfflineMode::Unknown;

            if (!player->IsValid())
                return ReturnCode::OfflineMode::Unknown;

            if (player->GetMainCha()->GetPlayer() != player)
                return ReturnCode::OfflineMode::Unknown;

            if (!g_Config.m_bOfflineMode)
                return ReturnCode::OfflineMode::Disabled;

            if (pCCha = player->GetCtrlCha(); !pCCha)
                return ReturnCode::OfflineMode::Unknown;

            if (!pCCha->IsLiveing())
                return ReturnCode::OfflineMode::Dead;

            if (auto map = pCCha->GetSubMap();
                map && !map->CanSavePos())
                return ReturnCode::OfflineMode::Refuse;

            if (pCCha->IsBoat())
                return ReturnCode::OfflineMode::Refuse;

            return ReturnCode::OfflineMode::Success;
        }();

        if (return_code != ReturnCode::OfflineMode::Success)
        {
            retpk.WriteInt64(static_cast<uint8_t>(return_code));
            break;
        }

        constexpr auto hour_in_ms = 60 * 60 * 1000;
        pCCha->_dwStallTick = GetTickCount() + (g_Config.m_dwStallTime * hour_in_ms);
        g_pGameApp->CanReceiveRequests(player->GetID(), false);
        player->SetCanReceiveRequests(false);
        retpk.WriteInt64(static_cast<uint8_t>(return_code));
        break;
    }
    default:
        return; //      
    }

    gt->SendData(retpk);
}

//
//  GateServer  
// 

bool GameServerApp::IsValidGate(int i)
{
    if (i < 0 || i > m_gtnum) throw std::logic_error("gate index out of range!");

    return m_gtarray[i].IsValid();
}

GateServer* GameServerApp::FindGate(char const* gt_name)
{
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            if (m_gtarray[i].GetName().compare(gt_name) == 0)
                return &m_gtarray[i];
        }
    }

    return NULL;
}


// 
//  Player 
// 

bool GameServerApp::AddPlayer(GatePlayer* gtplayer, GateServer* gt, unsigned long gtaddr)
{
    if (gt == nullptr || gtplayer == nullptr) return false;
    if (!gt->IsValid()) return false;

    gtplayer->SetGate(gt);
    gtplayer->SetGateAddr(gtaddr);

    auto* p = static_cast<CPlayer*>(gtplayer);
    auto [it, inserted] = gt->m_playerlist.insert(p);
    if (!inserted) {
        ToLogService("common", "when insert character, dbid {}, find it already in the list!", gtplayer->GetDBChaId());
        return false;
    }
    return true;
}

bool GameServerApp::DelPlayer(GatePlayer* gtplayer)
{
    if (gtplayer == nullptr) return false;

    GateServer* gt = gtplayer->GetGate();
    if (gt == nullptr || !gt->IsValid()) return false;

    gt->m_playerlist.erase(static_cast<CPlayer*>(gtplayer));
    return true;
}

bool GameServerApp::KickPlayer(GatePlayer* gtplayer, long lTimeSec)
{
	return KickPlayer2(gtplayer);
}

bool GameServerApp::KickPlayer2(GatePlayer *gtplayer)
{
	//  :   
	auto pkt = Corsairs::Net::Msg::serialize(Corsairs::Net::Msg::MtKickUserMessage{gtplayer->GetDBChaId(), (int64_t)gtplayer->GetGateAddr(), 1});
	gtplayer->GetGate()->SendData(pkt);
	return true;
}

// 
//    
// 

bool GameServerApp::SendToGroup(Corsairs::Net::WPacket& chginf)
{
    GateServer* pGate;

    for (int i = 0; i < m_gtnum; ++ i)
    {
        pGate = &m_gtarray[i];

        if (pGate->IsValid())
        {
			chginf.WriteInt64( 0 );
			pGate->SendData(chginf);
			return true;
        }
	}
    return true;
}

bool GameServerApp::SendToWorld(Corsairs::Net::WPacket& chginf)
{
    for (int i = 0; i < m_gtnum; ++i)
    {
        GateServer* pGate = &m_gtarray[i];
        if (!pGate->IsValid()) continue;

        Corsairs::Net::WPacket CChginf = chginf.Duplicate();
        short sCount = 0;

        for (CPlayer* p : pGate->m_playerlist)
        {
            CChginf.WriteInt64(p->GetDBChaId());
            CChginf.WriteInt64(p->GetGateAddr());
            ++sCount;
        }

        if (sCount > 0)
        {
            CChginf.WriteInt64(sCount);
            pGate->SendData(CChginf);
        }
    }

    return true;
}

bool GameServerApp::SendToClient(GatePlayer* player, Corsairs::Net::WPacket& pkt)
{
    if (player == NULL) return false;

    GateServer* pGate = player->GetGate();
    if (pGate != NULL)
    {
        pGate->SendData(pkt);
        return true;
    }
    else
    {
        return false;
    }
}

bool GameServerApp::SendToClient(Corsairs::Net::WPacket& pkt, std::span<CPlayer* const> recipients)
{
    if (recipients.empty()) return false;

    unsigned short usCount[MAX_GATE];
    Corsairs::Net::WPacket   CChginf[MAX_GATE];
    GateServer*    pValidGate[MAX_GATE];
    short          sValidGateNum = 0;
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            pValidGate[sValidGateNum] = &m_gtarray[i];
            usCount[sValidGateNum] = 0;
            CChginf[sValidGateNum] = pkt.Duplicate();
            sValidGateNum++;
        }
    }

    for (CPlayer* p : recipients)
    {
        if (!p) continue;
        if (p->GetGate() == nullptr)
        {
#ifdef defCOMMU_LOG
            ToLogService("common", "WARNING! pGate = NULL, atorID={}, gt_addr=0x{:x}",
                p->GetDBChaId(), p->GetGateAddr());
#endif
            continue;
        }

        for (int i = 0; i < sValidGateNum; ++ i)
        {
            if (p->GetGate() == pValidGate[i])
            {
                usCount[i]++;
                CChginf[i].WriteInt64(p->GetDBChaId());
                CChginf[i].WriteInt64(p->GetGateAddr());
                break;
            }
        }
    }

    for (int i = 0; i < sValidGateNum; i++)
    {
        if (usCount[i] > 0)
        {
            CChginf[i].WriteInt64(usCount[i]);
            pValidGate[i]->SendData(CChginf[i]);
        }
    }

    return true;
}

bool GameServerApp::SendToClient(Corsairs::Net::WPacket& pkt, int array_cnt, uplayer* uplayer_array)
{
    if (uplayer_array == NULL) return false;

    unsigned short usCount[MAX_GATE];
    Corsairs::Net::WPacket   CChginf[MAX_GATE];
    GateServer*    pValidGate[MAX_GATE];
    short          sValidGateNum = 0;
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            pValidGate[sValidGateNum] = &m_gtarray[i];
            usCount[sValidGateNum] = 0;
            CChginf[sValidGateNum] = pkt.Duplicate();
            sValidGateNum++;
        }
    }

    int j;
    for (int i = 0; i < array_cnt; ++ i)
    {
        if (uplayer_array[i].pGate == NULL)
        {
#ifdef defCOMMU_LOG
            ToLogService("common", "WARNING! pGate = NULL, atorID={}, gt_addr=0x{:x}",
                uplayer_array[i].m_dwDBChaId, uplayer_array[i].m_ulGateAddr);
#endif
            continue;
        }

        for (j = 0; j < sValidGateNum; ++ j)
        {
            if (uplayer_array[i].pGate == pValidGate[j])
            {
                usCount[j]++;
                CChginf[j].WriteInt64(uplayer_array[i].m_dwDBChaId);
                CChginf[j].WriteInt64(uplayer_array[i].m_ulGateAddr);
                break;
            }
        }
    }

    for (int i = 0; i < sValidGateNum; i++)
    {
        if (usCount[i] > 0)
        {
            CChginf[i].WriteInt64(usCount[i]);
            pValidGate[i]->SendData(CChginf[i]);
        }
    }

    return true;
}

bool GameServerApp::SendToGame(Corsairs::Net::WPacket& pkt, uplayer* uplyr)
{
    return uplyr->pGate->SendData(pkt);
}


GameServerApp* g_gmsvr;

// ============================================================================
// Ранее inline-методы из GameServerApp.h, вынесены в .cpp 2026-04-22.
// ============================================================================

GateServer::GateServer()  : m_pClient(nullptr), m_usPort(0), m_gtname("") {}
GateServer::~GateServer() { m_pClient = nullptr; m_gtname = ""; }

void  GateServer::SetClient(Corsairs::Net::TcpClient* client) { m_pClient = client; }
void  GateServer::Invalid()                         { m_pClient = nullptr; }
bool  GateServer::IsValid() {
	return m_pClient != nullptr && m_pClient->IsConnected();
}

std::string&    GateServer::GetIP()   { return m_strIp; }
unsigned short& GateServer::GetPort() { return m_usPort; }
std::string&    GateServer::GetName() { return m_gtname; }

bool GateServer::SendData(Corsairs::Net::WPacket& pkt) {
	if (IsValid()) {
		return m_pClient->Send(pkt);
	}
	return false;
}

int  GateServer::GetPlayerCount() const {
	return static_cast<int>(m_playerlist.size());
}

GateHandler::GateHandler() : _gateIndex(-1), _app(nullptr) {}

void GateHandler::Init(int gateIndex, GameServerApp* app) {
	_gateIndex = gateIndex;
	_app       = app;
}

char const*  GameServerApp::GetName() const { return m_strGameName.c_str(); }

Corsairs::Net::WPacket GameServerApp::GetWPacket()    { return Corsairs::Net::WPacket(256); }

void GameServerApp::BeginGetGate(void) {
	m_listcurgt = 0;
}

GateServer* GameServerApp::GetNextGate(void) {
	while (m_listcurgt < m_gtnum) {
		if (m_gtarray[m_listcurgt++].IsValid())
			return m_gtarray + (m_listcurgt - 1);
	}
	return nullptr;
}
