/* Generated by Together */

#ifndef ENTITY_H
#define ENTITY_H

#include "App/GameAppNet.h"
#include "Entity/Event.h"
#include "Network/CompCommand.h"

#include <source_location>

// Предобъявления: заголовок обязан быть самодостаточным. Раньше эти типы
// приходили случайным порядком включения через PCH, и смена компилятора
// это вскрыла.
// Предобъявление в области пространства имён. friend-объявление внутри
// класса не делает имя видимым для обычного поиска — только для ADL,
// поэтому использовать тип как SubMap* после него нельзя.
class SubMap;
class CPassengerMgr;

class CCharacter;
class CMoveAble;
class CFightAble;
class CItem;
class Monster;
class CAttachable;
class CEventEntity;
class CStateCellNode;
class CStateCell;
class CChaListNode;
class CEyeshotCell;
struct SSkillStateUnit;

namespace Corsairs::Common::Mission {
	class CNpc;
	class CEventEntity;
};

#define defENTITY_NAME_LEN	32
#define defLOG_NAME_LEN		64

/**
 * @alias
 */
class Entity {
	friend class SubMap;
	friend class CMgrUnit;
	friend class GameServerApp;
	friend class CCharacter;
	friend class CMoveAble;
	friend class CAction;
	friend class CFightAble;
	friend class CGameApp;
	friend class CChaSpawn;
	friend class CMapSwitchEntitySpawn;

public:
	// DEBUG-сборка логирует каждый Free с адресом+именем+call-site (source_location).
	// Помогает ловить двойные освобождения, висячие entity в eyeshot и т.п.
	void Free(std::source_location loc = std::source_location::current());
	void Initially();
	// ВАЖНО: Finally virtual — Free() живёт в Entity и вызывает Finally()
	// через this; без virtual диспатч уходит в Entity::Finally, минуя
	// CItem::Finally/CCharacter::Finally (а именно они снимают entity
	// с карты через SubMap::GoOut). Если забыть virtual — item после
	// Free() остаётся в eyeshot-cell как dangling.
	virtual void Finally();

	void          SetInitShape(const Corsairs::Util::Square& shape);
	const Corsairs::Util::Square& GetShape() const;

	void          SetPos(const Corsairs::Util::Point& pos);
	void          SetPos(std::int32_t lPosX, std::int32_t lPosY);
	const Corsairs::Util::Point&  GetPos() const;

	void          SetRadius(const long& lRadius);
	const long&   GetRadius() const;

	std::uint32_t    GetID() const;
	short         GetCat() const;
	void          SetID(std::uint32_t ulID);
	void          SetCat(short sCat);

	void          SetHandle(std::int32_t lHandle);
	std::int32_t     GetHandle(void);

	SubMap*       GetSubMap() const;
	SubMap*       GetSubMapFar();
	void          SetSubMap(SubMap* pCMap);

	short         GetAngle() const;
	void          SetAngle(short sAngle);

	const Corsairs::Util::Circle& GetTerritory();
	void          SetTerritory(Corsairs::Util::Circle& STerritory);

	void NotiChgToEyeshot(Corsairs::Net::WPacket chginf, bool bIncludeOwn = true);

	void          SetLogName(const char* szName);
	const char*   GetLogName();

	// _name — std::string в UTF-8 (сервер и клиент мигрированы на UTF-8).
	// GetName() возвращает const char* для C-совместимости (strcmp/strncpy/
	// printf и т.п. работают как раньше). Для std::string-кода —
	// GetNameStr() возвращает const std::string&.
	void               SetName(const std::string& name);
	void               SetName(const char* name);
	const char*        GetName() const;
	const std::string& GetNameStr() const;

	void          SetBirthCity(const char* cszName);
	const char*   GetBirthCity();

	void          SetBirthMap(const char* cszName);
	const char*   GetBirthMap();

	void          SetWitherTime(std::int32_t lWitherTime);
	void          SetResumeTime(std::int32_t lResumeTime);

	void          SetEvent(CEvent& CEvt);
	CEvent&       GetEvent(void);

	virtual void Run(std::uint32_t ulCurTick);
	Entity* SearchByIDInEyeshot(std::uint32_t culID);

	int16_t    GetExistState(void);
	void          SetExistState(int16_t sState);

	bool IsLiveing(void);

	int16_t    GetStopState(void);
	void          SetStopState(int16_t sState);

	bool          GetEyeshotAbility(void);
	void          SetEyeshotAbility(bool bEyeshot);

	void ActiveEyeshot(bool bActive = true);
	bool          IsValid(void);
	void          SetValid(bool bValid = true);

	std::uint16_t   GetAreaAttr(void);
	void          SetAreaAttr(std::uint16_t usAreaAttr);

	std::uint8_t    GetIslandID(void);
	void          SetIslandID(std::uint8_t uchIsland);

	bool          IsInSafeArea(void);

	CStateCellNode* EnterStateCell(CStateCell* pStateCell, CChaListNode* pEntiNode, bool bIsIn = false);
	void OutMgrUnit(CStateCellNode* pCMgrNode);
	void SetCenterMgrNode(CStateCellNode* pCMgrNode);
	SSkillStateUnit* GetAreaState(std::uint8_t uchStateID);
	void RefreshArea(void);
	void RefreshArea(Corsairs::Util::Point* pSrcPos);
	int16_t GetEyeshotWidth(void);

	int16_t    GetEyeshotHeight(void);

	bool IsInEyeshot(Entity* pCTarEnti);

	//
	virtual void GotoMapUnit();

	virtual CFightAble*            IsFightAble();
	virtual CMoveAble*             IsMoveAble();
	virtual CItem*                 IsItem();
	virtual Monster*               IsMonster();
	virtual CCharacter*            IsCharacter();
	virtual CAttachable*           IsAttachable();
	virtual Corsairs::Common::Mission::CNpc*         IsNpc();
	virtual Corsairs::Common::Mission::CEventEntity* IsEvent();

	void          BeginSee(Entity* obj);
	void          EndSee(Entity* obj);

	void WriteEventInfo(Corsairs::Net::WPacket& pk);
	void SynEventInfo(void);

	char m_szLogName[defLOG_NAME_LEN];
	std::uint32_t m_ID;

protected:
	Entity();

	virtual void ReflectINFof(Entity* srcent, Corsairs::Net::WPacket chginf);

	virtual bool overlap(long& xdist, long& ydist);

private:
	virtual const Corsairs::Util::Square& GetLapChkShape();

	virtual void OnBeginSee(Entity*);
	virtual void OnEndSee(Entity*);

	virtual void OnBeginSeen(CCharacter* pCCha) =0; //ToDo:
	virtual void OnEndSeen(CCharacter* pCCha) =0; //ToDo:
	virtual void AreaChange(void);

	bool EdgeOverlap(long& xdist, long& ydist);
	bool ObstacleOverlap(long& xdist, long& ydist);

public:
	bool m_bValid;

	std::int32_t m_lHandle;

	short m_cat;

	Corsairs::Util::Point m_lastpos;
	Corsairs::Util::Square m_shape;
	Corsairs::Util::Circle m_STerritory; //
	short m_sAngle;
	/**
	 * @label
	 * @labelDirection forward*/
	SubMap* m_submap;
	CStateCellNode *m_pCStateCellHead, *m_pCStateCellTail; //
	struct {
		Entity* m_pCEyeshotCellNext;
		Entity* m_pCEyeshotCellLast;
		CEyeshotCell* m_pCEyeshotHost;
	};

	char m_szBirthMap[MAX_MAPNAME_LENGTH];
	char m_szBirthCity[MAX_MAPNAME_LENGTH];

	CEvent m_CEvent;

	struct SExistCtrl {
		int16_t sState; // CompCommand.h EExistState
		int16_t sStopState; // EExistState enumEXISTS_WAITINGenumEXISTS_SLEEPING

		//
		std::int32_t lWitherTime; //
		std::int32_t lResumeTime; //
		std::uint32_t ulTick;
		//
	};

	std::string _name; // UTF-8
	SExistCtrl m_SExistCtrl;
	bool m_bActiveEyeshot;

	std::uint16_t m_usAreaAttr[2]; // 01CompCommand.hEAreaMask
	std::uint8_t m_ucIslandID[2]; // 01
};

extern void NotiPkToWorld(Corsairs::Net::WPacket chginf);

#endif //OBJECT_H
